# Script to run the CMMN survey analysis from the command line
#
# This file runs the complete set of scripts to do all the statistical analysis.
#
# Required input files are:
# Data file:
#     in-survey-data-file.csv - data file generated by copy-and-fix-file.r 
#
# Independent variable data (files generated by hand):
#     in-independent-variables.csv - file describing the independent variables
#     in-independent-variables-map.csv - mapping of independent variables to each of the 30 groups
#     in-weights.csv - file containing the weights to calculate CMMN Complexity (CC)
#
# Other files:
#     in-survey-var-names.csv - file exported from LimeSurvey
#
# Output files:
#     dataset-clean.csv - Clean data set that should be used to do any statistical analysis
#     dataset-clean-post.csv - Clean data set that should be used to do any statistical analysis using recalculated CC (iv.A.CC, iv.B.CC, and iv.C.CC)
#     dataset-all - Transformed and cleaned data set, but includes all collected data (included incompleted surveys)
#     CMMN-Convert-File.pdf - report of the convertion from in-survey-data-file.csv to out-clean-data.csv
#     CMMN-Sample.pdf - report with the analysis of the sample in the clean data set
#     CMMN-basic-stats.pdf - report of very basic statistics (mainly demographics)
#     CMMN-Weights.pdf - report of weight analysys and generated dataset-clean-post.cvs
library(knitr)
library(rmarkdown)

args <- commandArgs(trailingOnly = TRUE)
my.working.dir <- gsub("\\","/", as.character(args[1]), fixed = TRUE)
pandoc.path    <- gsub("\\","/", as.character(args[2]), fixed = TRUE)

setwd(my.working.dir)
print(paste("Working dir:",getwd()))


if(Sys.getenv("RSTUDIO_PANDOC")=="") Sys.setenv(RSTUDIO_PANDOC=pandoc.path)

print(paste("Pandoc path:",Sys.getenv("RSTUDIO_PANDOC")))

# Now let do the work (all the work will happen in the working directory, so no need for more paths)
# In here we use three functions, depending on the script type and the desired output, as follows:
#     render("name.Rmd", "pdf_document") for "<name>.Rmd" (R-Markdown files) to pdf output
#     knit2pdf("name.Rnw") for "<name>.Rnw" (Sweave files)  to pdf output
#     knit("name.Rnw") for "<name>.Rnw" (Sweave files)  to tex output (useful to produce chapters for the thesis)

render("CMMN-Convert-File.Rmd", "pdf_document") #, params = list(test=TRUE))
render("CMMN-Sample.Rmd", "pdf_document")
render("CMMN-basic-stats.Rmd", "pdf_document")

# This script will generate a new post-hoc file
render("CMMN-Weights.Rmd", "pdf_document")

# done
print("done")
